// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSA7vvfkVfML7SI5Hrq9ftjfY9-Xu_lH8',
    appId: '1:1089885608229:web:5d06c9e4146248d070a2cc',
    messagingSenderId: '1089885608229',
    projectId: 'gs02-30756',
    authDomain: 'gs02-30756.firebaseapp.com',
    storageBucket: 'gs02-30756.appspot.com',
    measurementId: 'G-ZV66C2EJJY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFA4pzvGw3JV-wIUT8cAZKEhHa_JGUtq0',
    appId: '1:1089885608229:android:a750ce784e62364e70a2cc',
    messagingSenderId: '1089885608229',
    projectId: 'gs02-30756',
    storageBucket: 'gs02-30756.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9USgJYyhWBF5BC_0aTtPxPTyQVI_Hc_0',
    appId: '1:1089885608229:ios:59927bf2690b873a70a2cc',
    messagingSenderId: '1089885608229',
    projectId: 'gs02-30756',
    storageBucket: 'gs02-30756.appspot.com',
    iosBundleId: 'com.example.gs2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9USgJYyhWBF5BC_0aTtPxPTyQVI_Hc_0',
    appId: '1:1089885608229:ios:499c2ebb1353c55370a2cc',
    messagingSenderId: '1089885608229',
    projectId: 'gs02-30756',
    storageBucket: 'gs02-30756.appspot.com',
    iosBundleId: 'com.example.gs2.RunnerTests',
  );
}
